/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Car1(props) {
  const group = useRef();
  const { currentColor } = props;
  const { nodes, materials } = useGLTF(
    "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/police-car/model.gltf"
  );

  useEffect(() => {
    materials.paintWhite.color.set(currentColor);
  }, [currentColor]);
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_body008.geometry}
        material={materials.paintWhite}
      />
      <mesh
        geometry={nodes.Mesh_body008_1.geometry}
        material={nodes.Mesh_body008_1.material}
      />
      <mesh
        geometry={nodes.Mesh_body008_2.geometry}
        material={nodes.Mesh_body008_2.material}
      />
      <mesh
        geometry={nodes.Mesh_body008_3.geometry}
        material={materials.lightFront}
      />
      <mesh
        geometry={nodes.Mesh_body008_4.geometry}
        material={nodes.Mesh_body008_4.material}
      />
      <mesh
        geometry={nodes.Mesh_body008_5.geometry}
        material={materials.window}
      />
      <mesh
        geometry={nodes.Mesh_body008_6.geometry}
        material={materials.carTire}
      />
      <mesh
        geometry={nodes.Mesh_body008_7.geometry}
        material={nodes.Mesh_body008_7.material}
      />
      <mesh
        geometry={nodes.Mesh_grill001.geometry}
        material={nodes.Mesh_grill001.material}
      />
      <mesh
        geometry={nodes.Mesh_grill001_1.geometry}
        material={nodes.Mesh_grill001_1.material}
      />
      <mesh
        geometry={nodes.Mesh_grill001_2.geometry}
        material={nodes.Mesh_grill001_2.material}
      />
      <mesh
        geometry={nodes.Mesh_grill001_3.geometry}
        material={nodes.Mesh_grill001_3.material}
      />
      <mesh
        geometry={nodes.Mesh_wheel_frontRight010.geometry}
        material={nodes.Mesh_wheel_frontRight010.material}
      />
      <mesh
        geometry={nodes.Mesh_wheel_frontRight010_1.geometry}
        material={nodes.Mesh_wheel_frontRight010_1.material}
      />
      <mesh
        geometry={nodes.Mesh_wheel_frontRight011.geometry}
        material={nodes.Mesh_wheel_frontRight011.material}
      />
      <mesh
        geometry={nodes.Mesh_wheel_frontRight011_1.geometry}
        material={nodes.Mesh_wheel_frontRight011_1.material}
      />
      <mesh
        geometry={nodes.Mesh_wheel_frontRight009.geometry}
        material={nodes.Mesh_wheel_frontRight009.material}
      />
      <mesh
        geometry={nodes.Mesh_wheel_frontRight009_1.geometry}
        material={nodes.Mesh_wheel_frontRight009_1.material}
      />
      <mesh
        geometry={nodes.Mesh_wheel_frontRight012.geometry}
        material={nodes.Mesh_wheel_frontRight012.material}
      />
      <mesh
        geometry={nodes.Mesh_wheel_frontRight012_1.geometry}
        material={nodes.Mesh_wheel_frontRight012_1.material}
      />
    </group>
  );
}

useGLTF.preload(
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/police-car/model.gltf"
);
