/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from "react";
import { useGLTF } from "@react-three/drei";

export default function Car3(props) {
  const group = useRef();
  const currentColor = props.currentColor;
  const { nodes, materials } = useGLTF(
    "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/zombie-car/model.gltf"
  );

  const coloredMaterials = useMemo(() => {
    const carMaterial = materials.Car.clone();
    carMaterial.color.set(currentColor);
    return { ...materials, Car: carMaterial };
  }, [materials, currentColor]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.1}>
        <mesh
          geometry={nodes.Cylinder018_Cylinder007.geometry}
          material={coloredMaterials.Car}
        />
        <mesh
          geometry={nodes.Cylinder018_Cylinder007_1.geometry}
          material={coloredMaterials.Windshield}
        />
      </group>
    </group>
  );
}

useGLTF.preload(
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/zombie-car/model.gltf"
);
