/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

export default function Chair(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/chair-wood/model.gltf"
  );

  const [targetX, setTargetX] = useState(0);
  const [newX, setNewX] = useState(2);

  // Use refs for performance optimization - no re-renders
  const currentX = useRef(0);

  // Smooth movement animation using lerp - optimized with refs
  useFrame(() => {
    if (group.current) {
      const newXValue = THREE.MathUtils.lerp(currentX.current, targetX, 0.1);
      currentX.current = newXValue;
      group.current.position.x = newXValue;
    }
  });

  const handleClick = () => {
    console.log("Chair clicked");
    setTargetX(targetX + newX);
    setNewX(-newX);
  };

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair.geometry}
        material={materials["BrownDark.052"]}
        onClick={handleClick}
      />
    </group>
  );
}

useGLTF.preload(
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/chair-wood/model.gltf"
);
